dependencies {
    testImplementation project(":template-logic")
    testImplementation project(":template-rest-service")
    testImplementation project(":template-rest-client")

    testImplementation "vg.lib:test:0.0.1-SNAPSHOT"
    testImplementation "vg.unique-id:unique-id-logic:0.0.1-SNAPSHOT"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.boot:spring-boot-starter-data-jpa"
    testImplementation "org.springframework.boot:spring-boot-starter-liquibase"
    testImplementation "org.springframework.boot:spring-boot-starter-web"
    testImplementation "org.springframework.kafka:spring-kafka"
    testImplementation "org.awaitility:awaitility"

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // MySQL
    testImplementation "org.springframework.boot:spring-boot-starter-jdbc:${spring_boot_version}"
    testRuntimeOnly "com.mysql:mysql-connector-j:${mysql_connector_version}"
}

test {
    useJUnitPlatform()
}